{{- if .Values.serviceAccount.create -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "tbhpa.serviceAccountName" . }}-auroscaller
rules:
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["patch", "get"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "tbhpa.serviceAccountName" . }}-auroscaller-rb
subjects:
- kind: ServiceAccount
  name: {{ include "tbhpa.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "tbhpa.serviceAccountName" . }}-auroscaller
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tbhpa.serviceAccountName" . }}
  labels:
    {{- include "tbhpa.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
